### ISSUE TITLE
ERROR: 'NoneType' object has no attribute 'yesterday_count

### ISSUE THREAD

**Issue by wandored** [wandored/stockcount#19]
after entering a count, if i select "Report" i get this error.  need to add an exception to handle this.

 --- Logging error ---
stockcount  | Traceback (most recent call last):
stockcount  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1463, in wsgi_app
stockcount  |     response = self.full_dispatch_request()
stockcount  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 872, in full_dispatch_request
stockcount  |     rv = self.handle_user_exception(e)
stockcount  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 870, in full_dispatch_request
stockcount  |     rv = self.dispatch_request()
stockcount  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 855, in dispatch_request
stockcount  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
stockcount  |   File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line 290, in decorated_view
stockcount  |     return current_app.ensure_sync(func)(*args, **kwargs)
stockcount  |   File "/stockcount/stockcount/main/routes.py", line 97, in report
stockcount  |     item.previous_count = yesterday_query.yesterday_count if yesterday_query.yesterday_count is not None else 0
stockcount  | AttributeError: 'NoneType' object has no attribute 'yesterday_count'
stockcount  |
stockcount  | During handling of the above exception, another exception occurred:
stockcount  |
stockcount  | Traceback (most recent call last):
stockcount  |   File "/usr/lib/python3.10/logging/__init__.py", line 1103, in emit
stockcount  |     stream.write(msg + self.terminator)
stockcount  | TypeError: a bytes-like object is required, not 'str'
stockcount  | Call stack:
stockcount  |   File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
stockcount  |     self._bootstrap_inner()
stockcount  |   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
stockcount  |     self.run()
stockcount  |   File "/usr/lib/python3.10/threading.py", line 953, in run
stockcount  |     self._target(*self._args, **self._kwargs)
stockcount  |   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
stockcount  |     work_item.run()
stockcount  |   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
stockcount  |     result = self.fn(*self.args, **self.kwargs)
stockcount  |   File "/usr/local/lib/python3.10/dist-packages/asgiref/sync.py", line 538, in thread_handler
stockcount  |     return func(*args, **kwargs)
stockcount  |   File "/usr/local/lib/python3.10/dist-packages/asgiref/wsgi.py", line 140, in run_wsgi_app
stockcount  |     for output in self.wsgi_application(environ, self.start_response):
stockcount  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1488, in __call__
stockcount  |     return self.wsgi_app(environ, start_response)
stockcount  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1466, in wsgi_app
stockcount  |     response = self.handle_exception(e)
stockcount  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 807, in handle_exception
stockcount  |     self.log_exception(exc_info)
stockcount  |   File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 828, in log_exception
stockcount  |     self.logger.error(
stockcount  | Message: 'Exception on /report/ [GET]'
stockcount  | Arguments: ()

**Comment by wandored** [comment]
this is likely caused by adding a new Item.   I added Chicken Wings and Crab Cakes to the Item list and created the first count today so there is no previous total
